# Generated by Django 3.1 on 2021-07-13 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0002_foodmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ddcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=30)),
                ('foodquant', models.CharField(max_length=10)),
                ('foodorder', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='orderhist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uemail', models.CharField(max_length=30)),
                ('ubillno', models.CharField(max_length=30)),
                ('udate', models.CharField(max_length=30)),
                ('uamount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='foodpic',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
