# Generated by Django 3.1 on 2021-07-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0004_auto_20210726_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhist',
            name='ubillno',
            field=models.CharField(default=343, max_length=30),
            preserve_default=False,
        ),
    ]
